### ISSUE TITLE
run at intervals

### ISSUE THREAD

**Issue by benjaminapetersen** [benjaminapetersen/origin-web-console-smoke-test#10]
We probably need to be able to set an interval for the smoke tests to run.  I imagine running the `protractor protractor.conf.js` command every 5 or 10 minutes would be helpful to ensure the web console is always responding.

We would probably not want to keep all of the `junit xml` files, but perhaps a limited number.  Something like log rotation.  For the short term we could just keep the most recent `x` number.

Then, the `/metrics` endpoint for prometheus can return more than a single pass/fail on the tests.  We would need to decide on the best [metric type](https://prometheus.io/docs/concepts/metric_types/) (currently is just a counter) to surface.

@jhadvig def open to any thoughts you might have!

**Comment by jhadvig** [comment]
Having couple of thoughts... ping me when you are online so we can talk :)

**Comment by benjaminapetersen** [comment]
#13 solves, I think.
