### ISSUE TITLE
Hitting /protractor with curl within the pod throws errors

### ISSUE THREAD

**Issue by benjaminapetersen** [benjaminapetersen/origin-web-console-smoke-test#14]
@jhadvig so I just did `docker exec -it <pod-id> /bin/bash` && then `curl localhost:3000/protractor`, which triggered a second round of the tests, but threw an error:

![screen shot 2018-04-06 at 3 50 20 pm](https://user-images.githubusercontent.com/280512/38441400-9704c53c-39b2-11e8-8682-ae5f72bcd902.png)

**Comment by jhadvig** [comment]
This is the block due to which the tests are failing for https://github.com/benjaminapetersen/origin-web-console-smoke-test/blob/master/test/server.js#L72-L74.
But since https://github.com/benjaminapetersen/origin-web-console-smoke-test/pull/23 is out that shouldnt be problem anymore.

**Comment by jhadvig** [comment]
Closing based on https://github.com/benjaminapetersen/origin-web-console-smoke-test/pull/23
