### ISSUE TITLE
Update test intervals

### ISSUE THREAD

**Issue by benjaminapetersen** [benjaminapetersen/origin-web-console-smoke-test#21]
We have the `/protractor` enpoint, we could probably update it to `/test` or`/run-tests` something generic if we keep it.  Then our meeting earlier suggested adding a `setInterval` function with a default timeout of `5 * 1000`, but allow this to be configured via an environment variable `INTERVAL=?`.

I think that covers what we talked about earlier today.  @jhadvig feel free to adjust :)

**Comment by benjaminapetersen** [comment]
If we keep the `/protractor` or `/test` endpoint, we need to ensure we protect against DOS attacks.  So definitely need to enforce a minimal time for the `setInterval`.

**Comment by jhadvig** [comment]
got rid of the endpoint and in https://github.com/benjaminapetersen/origin-web-console-smoke-test/pull/23
The tests are now running every 5 minutes if `TEST_INTERVAL` is not defined to other value.
Think we can close this one :)

**Comment by jhadvig** [comment]
But cant close it on my own :(

**Comment by benjaminapetersen** [comment]
Hmm still not?
