### ISSUE TITLE
Eliminate unnecessary files from git

### ISSUE THREAD

**Issue by benjaminapetersen** [benjaminapetersen/origin-web-console-smoke-test#25]
I think some `test_results` files were added before `.gitignore` was told to ignore them.  prob have to `git rm` them.

**Comment by jhadvig** [comment]
Updated in https://github.com/benjaminapetersen/origin-web-console-smoke-test/pull/23

**Comment by jhadvig** [comment]
Updated the gitignore file and remove unnecessary files in https://github.com/benjaminapetersen/origin-web-console-smoke-test/pull/23
Closing
